name: tinselcrm_mobile
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  bloc: ^8.1.1
  chopper: 7.2.0
  equatable: ^2.0.5
  firebase_analytics: ^10.8.10
  firebase_core: ^2.27.1
  firebase_crashlytics: ^3.4.19
  firebase_messaging: ^14.7.20
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_inappwebview: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.0.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  get_it: 7.6.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  vibration: ^1.7.6
  web_socket_channel: ^2.4.4
  webview_flutter: ^4.6.0

dev_dependencies:
  build_runner: ^2.4.8
  chopper_generator: 7.2.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/tinsel_icon.jpg"
