name: tinselcrm_mobile
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  animate_do: ^3.3.4
  bloc: ^8.1.1
  equatable: ^2.0.5
  firebase_core: ^2.27.1
  firebase_analytics: ^10.8.10
  firebase_messaging: ^14.7.20
  firebase_crashlytics: ^3.4.19
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_inappwebview: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  vibration: ^1.7.6
  web_socket_channel: ^2.4.4
  webview_flutter: ^4.5.0

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/tinsel_icon.jpg"
